### ISSUE TITLE
broken download links in summon-conjur.rb

### ISSUE THREAD

**Issue by bdhave** [cyberark/homebrew-tools#26]
they are two occurrences of missing character v before version number

  if OS.mac?
    url "https://github.com/cyberark/summon-conjur/releases/download/0.5.4/summon-conjur-darwin-amd64.tar.gz"
    sha256 "69fedac08d83f95b525eb645bb8ed7d867f5cf01d9f96dfd0254f51bf131fbf0"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/cyberark/summon-conjur/releases/download/0.5.4/summon-conjur-darwin-amd64.tar.gz"
    sha256 "b6aca46413b5ab4023f5cbd561d24ed3ae67b4727f77813d0bf5497bdb0c2707"
  end

must be (v added before 0.5.4)
  if OS.mac?
    url "https://github.com/cyberark/summon-conjur/releases/download/v0.5.4/summon-conjur-darwin-amd64.tar.gz"
    sha256 "69fedac08d83f95b525eb645bb8ed7d867f5cf01d9f96dfd0254f51bf131fbf0"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/cyberark/summon-conjur/releases/download/v0.5.4/summon-conjur-darwin-amd64.tar.gz"
    sha256 "b6aca46413b5ab4023f5cbd561d24ed3ae67b4727f77813d0bf5497bdb0c2707"
  end

**Comment by doodlesbykumbi** [comment]
@bdhave Thanks for submitting the issue. I messed up the brew formula by getting confused about the brew url_template in Go releaser.
> Annoyingly Go releaser strips the ‘v’ prefix on releases but not on snapshots. I saw the snapshot brew formula and mistakenly removed the ‘v’ from the brew url_template. See my question/complaint over at goreleaser/goreleaser#2114.

There's a [PR](https://github.com/cyberark/homebrew-tools/pull/27) to fix the broken URLs that should go in very soon.

**Comment by doodlesbykumbi** [comment]
@bdhave It should be fixed now.
