### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by AlexanderPavlenko** [cyberark/homebrew-tools#30]
```
$ brew tap cyberark/tools
==> Tapping cyberark/tools
Cloning into '/opt/homebrew/Library/Taps/cyberark/homebrew-tools'...
...
Error: Invalid formula: /opt/homebrew/Library/Taps/cyberark/homebrew-tools/summon-conjur.rb
formulae require at least a URL
Error: Invalid formula: /opt/homebrew/Library/Taps/cyberark/homebrew-tools/summon.rb
formulae require at least a URL
Error: Invalid formula: /opt/homebrew/Library/Taps/cyberark/homebrew-tools/terraform-provider-conjur.rb
formulae require at least a URL
Error: Cannot tap cyberark/tools: invalid syntax in tap!
```

amd64 binary seems to work fine, so maybe just amend the `Hardware::CPU.intel?` conditional in the formula.

**Comment by rpothier** [comment]
@AlexanderPavlenko Thanks for raising this issue! We're looking into it.

**Comment by rpothier** [comment]
Hi @AlexanderPavlenko we do not have any of the new Macs, I have made the changes for Summon to support the new Apple silicon, but cannot test it. Would you be able to try the summon image that is in code review https://github.com/cyberark/summon/pull/217

**Comment by AlexanderPavlenko** [comment]
Yes, but I didn't find a download link, only the `build` script.

**Comment by rpothier** [comment]
Hi @AlexanderPavlenko I made a draft release with the support for Apple hardware in Summon.
[draft release v0.8.4.1](https://github.com/rpothier/summon/releases/tag/v0.8.4.1)
Can you try this one - Thanks!

**Comment by AlexanderPavlenko** [comment]
Probably needs to be notarized, but seems functional otherwise.

**Comment by rpothier** [comment]
Thanks @AlexanderPavlenko !

**Comment by rpothier** [comment]
Summon, summon-conjur and terraform-provider-conjur  now support the new Apple hardware and will be updated in homebrew on the next release.

**Comment by jtuttle** [comment]
Homebrew has been updated. Apple silicon support should now be available in summon, summon-conjur and terraform-provider-conjur obtained via homebrew.
